---
title: "Assignment 3A: Reading Input"
author: "Brian Roepke"
date: "Sept 26, 2020"
output:
  html_document:
    df_print: paged
---
# Project Description

Now that you've learned about basic data manipulation in R, it's time to learn how to input a data file into R and learn the concept of data frame. 

Learn how to read various data files, such as text, CSV, and Excel. 

Refer to the Data Camp tutorial. You can always get help for a command by typing ?[command] (eg: ?read.csv) in the RStudio Console

1) Load the FaceBook datasets provided into data frames, and compare reading different file types by creating 3 data frames for each file type.

2) For the data frame for the CSV file, use **attach** to add it into your environment, then use basic functions such as: **str** , **summary** , **head** and **tail** 

3) For the data frame above, use the **names** function to show the column names. Notice column called  "X..of.Tags". The column from the raw file is actually "# of Tags". R converted this due to spaces. Rename this column to "Tags" using base R. (see: the Cookbook resource in supplementals). 

4) After using the **str function** to inspect the structure of the data frame, do you observe other issues with the expected data types? What issues and how do you solve it?

5) Create a data frame from the CSV data frame, using **subset**  that includes 3 fields: Gender, Posts, Friends. Include only valid Gender values (Male=1; Female=0). Use **head**  to display the top records. (see: Quick-R: Data Management)

6) We will use this dataset to do data visualization in the next session.  But you can start practicing a variety of data visualization appropriate for this dataset, such as histograms, pie charts, etc...  

Create a couple of graphs of your choice.(see: Quick R: Graphics)