---
title: "R Notebook"
output: html_notebook
---

https://tutorials.quanteda.io/advanced-operations/targeted-dictionary-analysis/

```{r message=FALSE, warning=FALSE}
library(quanteda)
library(lubridate)
require(quanteda.corpora)
```


```{r}
corp_news <- download("data_corpus_guardian")
```





```{r}
corp_news$year <- year(corp_news$date)
corp_news$month <- month(corp_news$date)
corp_news$week <- week(corp_news$date)

corp_news <- corpus_subset(corp_news, "year" >= 2016)
toks_news <- tokens(corp_news, remove_punct = TRUE)
```


```{r}
lengths(data_dictionary_LSD2015)
```


```{r}
toks_news_lsd <- tokens_lookup(toks_news, dictionary =  data_dictionary_LSD2015[1:2])
head(toks_news_lsd, 2)
```


```{r}
dfmat_news_lsd <- dfm(toks_news_lsd)
head(dfmat_news_lsd, 2)
```


```{r}
# get relevant keywords and phrases
eu <- c("EU", "europ*", "european union")

# only keep tokens specified above and their context of ±10 tokens
toks_eu <- tokens_keep(toks_news, pattern = phrase(eu), window = 10)

toks_eu <- tokens_lookup(toks_eu, dictionary = data_dictionary_LSD2015[1:2])

# create a document document-feature matrix and group it by weeks in 2016
dfmat_eu_lsd <- dfm(toks_eu) %>% 
    dfm_group(group = "week", fill = TRUE) 

matplot(dfmat_eu_lsd, type = "l", xaxt = "n", lty = 1, ylab = "Frequency")
grid()
axis(1, seq_len(ndoc(dfmat_eu_lsd)), ymd("2016-01-01") + weeks(seq_len(ndoc(dfmat_eu_lsd)) - 1))
legend("topleft", col = 1:2, legend = c("Negative", "Positive"), lty = 1, bg = "white")
```

```{r}
n_eu <- ntoken(dfm(toks_eu, group = toks_eu$week))
plot((dfmat_eu_lsd[,2] - dfmat_eu_lsd[,1]) / n_eu, 
     type = "l", ylab = "Sentiment", xlab = "", xaxt = "n")
axis(1, seq_len(ndoc(dfmat_eu_lsd)), ymd("2016-01-01") + weeks(seq_len(ndoc(dfmat_eu_lsd)) - 1))
grid()
abline(h = 0, lty = 2)
```


```{r}
immig <- c("immig*", "migra*")
toks_immig <- tokens_keep(toks_news, pattern = phrase(immig), window = 10)

toks_immig <- tokens_lookup(toks_immig, dictionary = data_dictionary_LSD2015[1:2])

# create a document document-feature matrix and group it by weeks in 2016
dfmat_immig_lsd <- dfm(toks_immig) %>% 
    dfm_group(group = "week", fill = TRUE) 

matplot(dfmat_immig_lsd, type = "l", xaxt = "n", lty = 1, ylab = "Frequency")
grid()
axis(1, seq_len(ndoc(dfmat_immig_lsd)), ymd("2016-01-01") + weeks(seq_len(ndoc(dfmat_immig_lsd)) - 1))
legend("topleft", col = 1:2, legend = c("Negative", "Positive"), lty = 1, bg = "white")
```




